# Generated by Django 5.0.7 on 2024-07-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_assignment_grade_assignment_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
